-- core configs
require 'config.options'
require 'config.mappings'
require 'config.autocmds'

-- my plugins
-- require 'sonix.cowboy'
-- require 'sonix.sql-runner'
require 'sonix.dooin'

-- plugins
require 'plugins.gitsigns'
require 'plugins.which-key'
require 'plugins.snacks'
require 'plugins.lsp'
require 'plugins.blink'
require 'plugins.conform'
require 'plugins.lint'
require 'plugins.lualine'
require 'plugins.mini'
require 'plugins.noice'
require 'plugins.solarized-osaka'
require 'plugins.nvim-treesitter'
require 'plugins.dap'
require 'plugins.lazydev'
require 'plugins.vim-sleuth'
require 'plugins.vim-tmux-navigator'
require 'plugins.vim-dadbob'
require 'plugins.oil'
require 'plugins.render-markdown'
require 'plugins.im-switch'
require 'plugins.transparent'
require 'plugins.markdown-preview'
require 'plugins.gitlinker'
-- require 'plugins.checkmate'
